Repository sqlitebrowser/sqlitebrowser, pull requests merged in 2018-07, with the labels that each got.

#1422 Sql export
  src/ExtendedTableWidget.cpp
  src/ExtendedTableWidget.h
  src/icons/icons.qrc
  src/icons/page_copy_sql.png
Labels: enhancement

#1404 Add automatic crypted databases open via dotenvs
  CMakeLists.txt
  src/CipherDialog.cpp
  src/CipherDialog.h
  src/CipherSettings.cpp
  src/CipherSettings.h
  src/DotenvFormat.cpp
  src/DotenvFormat.h
  src/MainWindow.cpp
  src/Settings.h
  src/sqlitedb.cpp
  src/sqlitedb.h
  src/src.pro
  src/tests/CMakeLists.txt
Labels: enhancement

#1456 i18n: Start Polish translation
  CMakeLists.txt
  src/src.pro
  src/translations/sqlb_pl.ts
  src/translations/translations.qrc
Labels: response requested, translation

#1455 User SQL log with results and other fixes and improvements in Execute SQL
  src/MainWindow.cpp
Labels: SQL, bug, enhancement
